"""
DualGuard PII 감지 테스트 및 MD 리포트 생성
"""
import sys
from pathlib import Path
from datetime import datetime

# 프로젝트 루트 추가
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from agent.core.pattern_matcher import detect_pii, calculate_risk, get_risk_action


def test_case(name, text, expected_count, expected_risk):
    """단일 테스트 케이스 실행"""
    result = detect_pii(text)
    risk = calculate_risk(result['found_pii'])

    count_ok = result['count'] == expected_count
    risk_ok = risk['final_risk'] == expected_risk
    status = 'PASS' if (count_ok and risk_ok) else 'FAIL'

    pii_list = [p['name_ko'] for p in result['found_pii']]

    return {
        'name': name,
        'text': text,
        'expected_count': expected_count,
        'actual_count': result['count'],
        'expected_risk': expected_risk,
        'actual_risk': risk['final_risk'],
        'escalation': risk.get('escalation_reason') or '-',
        'pii_found': pii_list,
        'status': status
    }


def run_all_tests():
    """모든 테스트 실행"""
    tests = []

    # 1. 기본 PII 감지 (단일)
    tests.append(test_case('신용카드 단일', '신용카드 5361-1234-5678-9012 입니다', 1, 'HIGH'))
    tests.append(test_case('주민번호 단일', '주민번호 900101-1234567 알려줄게', 1, 'CRITICAL'))
    tests.append(test_case('계좌번호 단일', '계좌번호 110-123-456789로 보내줘', 1, 'MEDIUM'))
    tests.append(test_case('전화번호 단일', '전화번호 010-1234-5678 입니다', 1, 'LOW'))
    tests.append(test_case('이메일 단일', '이메일 test@example.com 입니다', 1, 'LOW'))

    # 2. 조합 위험도 테스트 (CRITICAL 상향)
    tests.append(test_case('카드+CVC', '카드 1234-5678-9012-3456 CVC 123', 2, 'CRITICAL'))
    tests.append(test_case('카드+CVC+유효기간', '카드 1234-5678-9012-3456 CVC 123 유효기간 12/26', 3, 'CRITICAL'))

    # 3. 복합 PII (여러 종류)
    tests.append(test_case('계좌+전화', '계좌 110-123-456789 전화 010-1234-5678', 2, 'MEDIUM'))
    tests.append(test_case('주민+전화+계좌', '주민 900101-1234567 폰 010-1234-5678 계좌 110-123-456789', 3, 'CRITICAL'))

    # 4. 안전한 메시지 (PII 없음)
    tests.append(test_case('일반 대화', '오늘 점심 뭐 먹을까?', 0, 'LOW'))
    tests.append(test_case('숫자 포함 대화', '회의실 302호에서 3시에 만나요', 0, 'LOW'))
    tests.append(test_case('날짜 언급', '2024년 12월 25일에 만나요', 0, 'LOW'))

    # 5. 엣지 케이스
    tests.append(test_case('여권번호', '여권번호 M12345678 입니다', 1, 'CRITICAL'))
    tests.append(test_case('운전면허', '면허번호 11-12-345678-90', 1, 'HIGH'))
    tests.append(test_case('외국인등록번호', '외국인등록 900101-5123456', 1, 'CRITICAL'))

    # 6. 변형 패턴
    tests.append(test_case('전화번호 점 구분', '폰번호 010.1234.5678 이야', 1, 'LOW'))
    tests.append(test_case('카드번호 공백없음', '카드1234567890123456입니다', 1, 'HIGH'))

    return tests


def generate_md_report(tests):
    """MD 리포트 생성"""
    pass_count = sum(1 for t in tests if t['status'] == 'PASS')
    fail_count = sum(1 for t in tests if t['status'] == 'FAIL')

    md = f"""# DualGuard PII 감지 테스트 결과

**테스트 일시**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**테스트 버전**: pattern_matcher.py (우선순위 매칭 적용)

---

## 테스트 요약

| 항목 | 결과 |
|------|------|
| 총 테스트 | {len(tests)}개 |
| 성공 (PASS) | {pass_count}개 |
| 실패 (FAIL) | {fail_count}개 |
| 성공률 | {pass_count/len(tests)*100:.1f}% |

---

## 상세 결과

| 상태 | 테스트명 | 예상 PII | 실제 PII | 예상 위험도 | 실제 위험도 |
|------|----------|----------|----------|-------------|-------------|
"""

    for t in tests:
        status_icon = '✅' if t['status'] == 'PASS' else '❌'
        md += f"| {status_icon} | {t['name']} | {t['expected_count']} | {t['actual_count']} | {t['expected_risk']} | {t['actual_risk']} |\n"

    md += """
---

## 입력 텍스트 및 감지 결과

"""

    for t in tests:
        status_icon = '✅' if t['status'] == 'PASS' else '❌'
        md += f"### {status_icon} {t['name']}\n\n"
        md += f"- **입력**: `{t['text']}`\n"
        md += f"- **감지된 PII**: {', '.join(t['pii_found']) if t['pii_found'] else '없음'}\n"
        md += f"- **위험도**: {t['actual_risk']}\n"
        if t['escalation'] != '-':
            md += f"- **상향 이유**: {t['escalation']}\n"
        md += "\n"

    md += """---

## 주요 개선사항 (v1.3.0)

1. **우선순위 매칭**: 신용카드/주민번호를 먼저 감지하여 중복 오탐 방지
2. **중복 범위 제외**: 이미 매칭된 문자열 범위는 다른 패턴으로 재감지 안 함
3. **조합 규칙 추가**:
   - 카드+CVC → CRITICAL
   - 카드+CVC+유효기간 → CRITICAL
   - 이름+운전면허 → HIGH
4. **CVC/CVV 패턴 추가**: 보안코드 감지
5. **카드 유효기간 패턴 추가**: 만료일 감지

---

*Generated by DualGuard Test Suite*
"""

    return md


def main():
    print("=" * 60)
    print("DualGuard PII Detection Test")
    print("=" * 60)
    print()

    # 테스트 실행
    tests = run_all_tests()

    # 콘솔 출력
    for t in tests:
        status_icon = '[PASS]' if t['status'] == 'PASS' else '[FAIL]'
        print(f"{status_icon} {t['name']}: PII {t['actual_count']}, Risk {t['actual_risk']}")

    print()
    pass_count = sum(1 for t in tests if t['status'] == 'PASS')
    print(f"Result: {pass_count}/{len(tests)} passed ({pass_count/len(tests)*100:.1f}%)")
    print()

    # MD 파일 생성
    md_content = generate_md_report(tests)

    output_path = project_root / "agent" / "tests" / "TEST_REPORT.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"리포트 생성: {output_path}")


if __name__ == "__main__":
    main()
